export const FILTER_FILMS = 'FILTER_FILMS';
export const GET_FILMS = 'GET_FILMS';
export const GET_FILMS_SUCCEED = 'GET_FILMS_SUCCEED';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const SORT_FILMS = 'SORT_FILMS';
export const SORT_FILMS_DONE = 'SORT_FILMS_DONE';

export default {
  FILTER_FILMS,
  GET_FILMS,
  GET_FILMS_SUCCEED,
  SET_LOADING_STATUS,
  SORT_FILMS,
  SORT_FILMS_DONE,
};
